language: elixir
elixir:
  - 1.2.0-rc.0
otp_release:
  - 18.1
addons:
  postgresql: "9.4"
services:
  - mysql
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
script:
  - mix test
  - ECTO_POOL=poolboy mix test.adapters
  - ECTO_POOL=sojourn_broker mix test.adapters
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
